### ISSUE TITLE
Attaching terminal to pod displaying debugging information

### ISSUE THREAD

**Issue by montgomerybc** [Azure/vscode-kubernetes-tools#941]
# Extension Version
v0.0.8

# VSCode Version
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

# Repro
Navigate to pod: CLUSTERS / Workloads / Deployments / my-k8s-deployment / my-k8s-pod
Right Click / Terminal

Following is rendered to the VS Code terminal
```
I0425 13:15:55.788294   12372 log.go:181] (0xc000664000) (0xc0008441e0) Create stream
I0425 13:15:55.788294   12372 log.go:181] (0xc000664000) (0xc0008441e0) Stream added, broadcasting: 1
I0425 13:15:55.862173   12372 log.go:181] (0xc000664000) Reply frame received for 1
I0425 13:15:55.862173   12372 log.go:181] (0xc000664000) (0xc000522000) Create stream
I0425 13:15:55.862173   12372 log.go:181] (0xc000664000) (0xc000522000) Stream added, broadcasting: 3
I0425 13:15:55.967954   12372 log.go:181] (0xc000664000) Reply frame received for 3
I0425 13:15:55.967954   12372 log.go:181] (0xc000664000) (0xc0007b8000) Create stream
I0425 13:15:55.967954   12372 log.go:181] (0xc000664000) (0xc0007b8000) Stream added, broadcasting: 5
I0425 13:15:56.035884   12372 log.go:181] (0xc000664000) Reply frame received for 5
I0425 13:15:56.035884   12372 log.go:181] (0xc000664000) (0xc0005220a0) Create stream
I0425 13:15:56.035884   12372 log.go:181] (0xc000664000) (0xc0005220a0) Stream added, broadcasting: 7
I0425 13:15:56.131866   12372 log.go:181] (0xc000664000) Reply frame received for 7
I0425 13:15:56.131866   12372 log.go:181] (0xc000664000) Data frame received for 5
I0425 13:15:56.131866   12372 log.go:181] (0xc0007b8000) (5) Data frame handling  
I0425 13:15:56.131866   12372 log.go:181] (0xc0005220a0) (7) Writing data frame   
I0425 13:15:56.165688   12372 log.go:181] (0xc000664000) Data frame received for 5
I0425 13:15:56.165688   12372 log.go:181] (0xc0007b8000) (5) Data frame handling
I0425 13:15:56.165688   12372 log.go:181] (0xc0007b8000) (5) Data frame sent
/app # I0425 13:15:56.165688   12372 log.go:181] (0xc000522000) (3) Writing data frame
I0425 13:15:56.167688   12372 log.go:181] (0xc000664000) Data frame received for 5
I0425 13:15:56.167688   12372 log.go:181] (0xc0007b8000) (5) Data frame handling
I0425 13:15:56.167688   12372 log.go:181] (0xc0007b8000) (5) Data frame sent
/app #
```

Every character I type will display 4 lines of logging make the terminal unusable

I have uninstalled/restarted/installed - same behaviour

**Comment by itowlson** [comment]
@montgomerybc Sorry for the lack of reply - this was filed on the AKS repo but I am pretty sure it is an issue with the core Kubernetes extension.  I have transferred it.

@lstocchi @Tatsinnit does either of you have bandwidth to look at this please?

**Comment by lstocchi** [comment]
@itowlson maybe next week but i cannot guarantee anything. I'll keep you updated.

**Comment by Tatsinnit** [comment]
💡 loop back, I am **not** able to replicate this issue, I am on `version: 1.3.3` Might be in the new version it is fixed? since this specific case for version `0.0.8`


<img width="947" alt="Screen Shot 2021-06-08 at 3 24 11 PM" src="https://user-images.githubusercontent.com/6233295/121118776-8b106f80-c86e-11eb-8f4a-eaebacd8e989.png">


FYI: cc: @itowlson & @lstocchi for information share and In case anyone have replication with new version of extension. Thank you 🙏

**Comment by montgomerybc** [comment]
Still happens, but it _must_ be a conflict with another extension.  If I
disable _all_ extensions except those needed by k8s, it works.  I'll bisect
my way down to find the extension causing grief and reply here.

**Comment by fernandodevelon** [comment]
@montgomerybc did you find the solution? 
I also have the same problem.

**Comment by montgomerybc** [comment]
I did not.  For unrelated reasons, I switched to a new machine, and when I
installed the same set of extensions, it no longer happens.  Sorry I can't
be more helpful

-Dave

**Comment by lstocchi** [comment]
@fernandodevelon could you share the list of extensions you have installed in vscode?

**Comment by montgomerybc** [comment]
FWIW, these are mine:

PS> code --list-extensions
alefragnani.Bookmarks
batisteo.vscode-django
bierner.markdown-mermaid
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
eamodio.gitlens
hediet.vscode-drawio
KevinRose.vsc-python-indent
lonefy.vscode-JS-CSS-HTML-formatter
magicstack.MagicPython
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-wsl
ms-vscode.powershell
njpwerner.autodocstring
PrateekMahendrakar.prettyxml
qcz.text-power-tools
redhat.vscode-yaml
sleistner.vscode-fileutils
VisualStudioExptTeam.vscodeintellicode
VisualStudioOnlineApplicationInsights.application-insights
wholroyd.jinja
yzhang.markdown-all-in-one

**Comment by fernandodevelon** [comment]
```
alefragnani.Bookmarks
austenc.tailwind-docs
bee.git-temporal-vscode
bradlc.vscode-tailwindcss
capaj.vscode-standardjs-snippets
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
Chukwuamaka.csvtojson-converter
cschleiden.vscode-github-actions
dbaeumer.vscode-eslint
dinhani.copy-on-select
dnicolson.binary-plist
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
eriklynd.json-tools
esbenp.prettier-vscode
formulahendry.code-runner
gencer.html-slim-scss-css-class-completion
Gruntfuggly.todo-tree
hilleer.yaml-plus-json
Hridoy.adonisjs-snippets
humao.rest-client
incleaf.vuetypes-snippets
ineptian.simple-placeholder-images
JakeWilson.vscode-placeholder-images
janisdd.vscode-edit-csv
jcbuisson.vue
jock.svg
JonaNeumeier.date-to-format
jsynowiec.vscode-insertdatestring
khaeransori.json2csv
lihui.vs-color-picker
marclipovsky.string-manipulation
mechatroner.rainbow-csv
Meezilla.json
mhutchie.git-graph
mikestead.dotenv
mishannn.vuex-suggest
mitchdenny.ecdc
mohsen1.prettify-json
mongodb.mongodb-vscode
mrmlnc.vscode-duplicate
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-it
ms-kubernetes-tools.vscode-kubernetes-tools
ms-vscode-remote.remote-containers
ms-vscode.sublime-keybindings
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
nidu.copy-json-path
octref.vetur
oysun.vuehelper
pavittarx.moleculer-snippets
raidou.calc
redhat.vscode-yaml
rid9.datetime
sdras.vue-vscode-snippets
Shelex.vscode-cy-helper
sibiraj-s.vscode-scss-formatter
standard.vscode-standard
stef-k.adonis-js-goto-controller
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-italian
TheHolyCoder.swagger-tools
titiaiev.vue-docs
tomphilbin.lodash-snippets
Tyriar.lorem-ipsum
vikash-ck-dev.vscode-convert
vincaslt.highlight-matching-tag
wix.vscode-import-cost
wxt2005.date-preview
xk0der.vsc-postman-collection-syntax
ZaferAYAN.lorem-picsum
ZainChen.json
```

**Comment by lstocchi** [comment]
Tried by installing those extensions but i didn't face it. 
I tried what it's written here and i was able to replicate it https://stackoverflow.com/questions/43144822/disabling-network-logs-on-kubernetes-when-running-kubectl-exec . Could you please verify if you have the DEBUG env variable set? :crossed_fingers: @fernandodevelon

**Comment by SethFalco** [comment]
I have the same problem, and confirm I don't have the `DEBUG` environment variable set.

```
Version: 1.70.0-insider
Commit: 3da2d669a4dcf93938a262ba92f50b128ca7262a
Date: 2022-07-20T05:17:45.988Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.10.0-16-amd64 snap
```

* mongodb.mongodb-vscode
* lokalise.i18n-ally
* ms-kubernetes-tools.vscode-kubernetes-tools
* ms-azuretools.vscode-docker
* ryanluker.vscode-coverage-gutters
* vscode.json-language-features
* vscode.typescript-language-features
* flowtype.flow-for-vscode
* vscode.git
* rebornix.ruby
* mtxr.sqltools
* esbenp.prettier-vscode
* Dart-Code.dart-code
* redhat.vscode-yaml
* ms-vscode-remote.remote-containers
* SonarSource.sonarlint-vscode
* GraphQL.vscode-graphql
* vscode.github-authentication
* slevesque.vscode-hexdump
* EditorConfig.EditorConfig
* stylelint.vscode-stylelint
* dbaeumer.vscode-eslint
* ms-vscode.live-server
* vscode.emmet
* vscode.grunt
* vscode.npm
* vscode.merge-conflict
* vscode.extension-editing
* vscode.gulp
* vscode.ipynb
* vscode.configuration-editing
* vscode.debug-auto-launch
* vscode.git-base
* vscode.jake
* waderyan.gitblame
* mrorz.language-gettext
* mtxr.sqltools-driver-mysql
* nhoizey.gremlins
* mrcrowl.hg

Later I can try investigate this further and see what's wrong.

I can confirm what I connect directly via `kubectl exec -it {} -- /bin/bash` in my terminal, I do not have this issue.

**Comment by jomel** [comment]
> the solu
I had the same issue, and was able to narrow it down to the extension "MongoDB for VS Code" ( mongodb.mongodb-vscode ) 

Once I disabled the extension, exited any already-running terminals, and reloaded VS Code window, my new terminal outputs were back to normal.

I was running kubernetes extension version 1.3.15
I was running the Mondogb extension version 1.3.1
I did not have DEBUG variable set

@SethFalco  @montgomerybc @fernandodevelon : could you check if disabling the mongoDb extension fixes this for you guys?

**Comment by samsafay** [comment]
@jomel Thanks I can confirm that by removing MongoDB extension the problem goes away!

**Comment by berkunal** [comment]
@jomel I had the same issue with no DEBUG env var set. Didn't think it could be related to another extension. Big thanks!

**Comment by jongbeom-kwon** [comment]
I had a problem using direnv. DEBUG was set to True in the .env file of my project environment. Hope this helps someone.
